buildFuture = true
languageCode = 'en-us'
title = "Nelson Community Land Trust"
disableKinds = ['taxonomy', 'term']

[params]
description = "Nelson Community Land Trust Society"
subtitle = ""

[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "Jam Factory"
url = "/jam-factory"
weight = 2

[[menus.main]]
name = "About"
url = "/about"
weight = 3
