buildFuture = true
languageCode = 'en-us'
title = "Nelson Community Land Trust"
disableKinds = ['taxonomy', 'term']

[params]
description = "Holding Space for Nelson's Creatives"
subtitle = ""

[[menus.main]]
name = "News"
url = "/news"
weight = 2

[[menus.main]]
name = "606"
url = "/606"
weight = 3

[[menus.main]]
name = "Jam Factory"
url = "/jam-factory"
weight = 4

[[menus.main]]
name = "About"
url = "/about"
weight = 5
